### PR TITLE
Fix 4.15.1 compilation

### PR DESCRIPTION
**Pull request by TTimo**
I had to make these changes in order to compile against 4.15.1 (full engine from source) - see https://forums.unrealengine.com/showthread.php?137015-4-15-C-Transition-Guide

### CODE REVIEW

**Comment by ufna** [comment]
What's the exact issue you've met once you try to compile it? Its not the right method to put all PCH includes into header files.

**Comment by TTimo** [comment]
My understanding is that the PCH are implicit and managed automatically now, so naming headers '*PCH.h' won't matter anymore, there's just no PCH control exposed anymore (see https://forums.unrealengine.com/showthread.php?129610-Iwyu&p=627943&viewfull=1#post627943).

UBT gives an error and bails because it wants every .cpp file to start by including a header with the same name. E.g. "VaRestJsonObject.cpp needs to include VaRestJsonObject.h first, VaRestJsonValue.cpp needs to include VaRestJsonValue.h first, etc."

**Comment by ufna** [comment]
Yep, thanks for pointing to this, I'll merge your pull request now and then split *PCH, because it's just not a plain IWYU model when you have one big header with all includes :)

Also, its strange, but I can't reproduce "compilation issue" itself :) I use the plugin in few projects (even 4.16 now) and all is okay.

**Comment by ufna** [comment]
I've moved this pull request to feature branch and reverted from develop, because it makes compilation broken for me. I'm not sure how to reproduce the issue you've mentioned

**Pull request merged**
